joint_limits:
  mico_joint_finger_1:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  mico_joint_1:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  mico_joint_2:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  mico_joint_6:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  mico_joint_finger_2:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  mico_joint_5:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  mico_joint_3:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  mico_joint_4:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
