joint_limits:
  jf1:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  j1:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  j2:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  j6:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  jf2:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  j5:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  j3:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0
  j4:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: false
    max_acceleration: 0