joint_limits:
  jf1:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  j1:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  j2:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  j6:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  jf2:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  j5:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  j3:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
  j4:
    has_velocity_limits: true
    max_velocity: 2.9217
    has_acceleration_limits: true
    max_acceleration: 0.251327412288
