summit_xl_mico:

  # Summit XL
  joint_blw_velocity_controller:
#    type: velocity_controllers/JointVelocityController
    type: effort_controllers/JointEffortController
    joint: joint_back_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_brw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_back_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_frw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_front_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_flw_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_front_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

#  joint_pan_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint_camera_pan
#    pid: {p: 100.0, i: 0.01, d: 50.0}
    
#  joint_tilt_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: joint_camera_tilt
#    pid: {p: 100.0, i: 0.01, d: 50.0}

  # Mico Arm  
  j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_1
    pid: {p: 500.0, i: 20.0, d: 5.0}

  j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_2
    pid: {p: 700.0, i: 30.0, d: 5.0}
  
  j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_3
    pid: {p: 800.0, i: 30, d: 0.0}

  j4_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_4
    pid: {p: 100.0, i: 20, d: 5.0}

  j5_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_5
    pid: {p: 100.0, i: 15, d: 0.0}

  jhand_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_6
    pid: {p: 100.0, i: 10, d: 1.0}

  jf1_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_finger_1
    pid: {p: 50.0, i: 0.1, d: 0.1}
    
  jf2_position_controller:
    type: effort_controllers/JointPositionController
    joint: mico_joint_finger_2
    pid: {p: 50.0, i: 0.1, d: 0.1}
    
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
